name: Rust-Build-&-Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Audit
      run: cargo audit -v
    - name: Clippy
      run: cargo clippy -v

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
